name: Bot Chạy Hàng Ngày

on:
  schedule:
    - cron: '0 0 * * *' # 7h sáng VN
  workflow_dispatch: # Nút chạy thủ công

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Tải code
        uses: actions/checkout@v3

      - name: Cài đặt Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cài thư viện
        run: pip install requests feedparser beautifulsoup4

      - name: Chạy Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
